version: '3.8'
services:
  db:
    image: postgres:15-alpine
    container_name: nexus_db
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=mysecretpassword
      - POSTGRES_DB=nexus_crm
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d nexus_crm"]
      interval: 10s
      timeout: 5s
      retries: 5
  crm-core-service:
    build: ./services/crm-core-service
    container_name: crm_core_api
    restart: on-failure
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:mysecretpassword@db:5432/nexus_crm
    volumes:
      - ./services/crm-core-service:/app
    depends_on:
      db:
        condition: service_healthy
volumes:
  postgres_data:
