# docker-compose.yml
services:
  db:
    image: postgres:15
    container_name: nexus_db
    restart: always
    environment:
      POSTGRES_USER: nexus
      POSTGRES_PASSWORD: nexus
      POSTGRES_DB: nexusdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  fastapi:
    build:
      context: ./src/backend
    container_name: nexus_api
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./src:/app
    ports:
      - "8000:8000"
    depends_on:
      - db

  streamlit:
    build:
      context: ./src/frontend
    container_name: nexus_ui
    command: streamlit run main_dashboard.py --server.port 8501
    volumes:
      - ./src:/app
    ports:
      - "8501:8501"
    depends_on:
      - db

volumes:
  postgres_data:
